name: Docker Image CI

on:
  release:
    types: [created]

env:
  DOCKER_IMAGE_TAG: ${{ secrets.DOCKER_USERNAME }}/pptr-docker:${{ env.GITHUB_REF }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image ${{ env.DOCKER_IMAGE_TAG }}
      run: docker build . -t ${{ env.DOCKER_IMAGE_TAG }}
    - name: Publish to Dockerhub
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker upload ${{ env.DOCKER_IMAGE_TAG }}
