name: Docker Image CI

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . -t xgui3783/pptr-docker:${{ github.GITHUB_REF }}
    - name: Publish to Dockerhub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} && docker upload ${{ secrets.DOCKER_USERNAME }}/pptr-docker:${{ github.GITHUB_REF }}
